name: 📑 Release Page

permissions: write-all
on:
  push:
    tags:
      - "v*"

jobs:
  tagged-release:
    name: 📑 Release Page
    runs-on: "ubuntu-latest"
    steps:
      - name: 📑 Create Release Page
        uses: ncipollo/release-action@v1
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          generateReleaseNotes: true
          makeLatest: true
